[project]
name = "standalert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "bs4>=0.0.2",
    "python-dotenv>=1.0.1",
    "pyvirtualdisplay>=3.0",
    "selenium>=4.28.1",
]
